### ISSUE TITLE
TODO: api 연결

### ISSUE THREAD

**Issue by hwisaac** [KDT-Final-Team4/salarying-fe#57]
## 세부 내용
- [ ] company
- [ ] company/jobposting
- [ ] company/jobposting/2
- [ ] company/jobposting/new
- [ ] company/applicant-management
- [ ] company/applicant-management/category/1
- [ ] company/notification
